#!/bin/bash
# Import words from wortlist file into main wordlists.

set -u

export PATH=/bin:/usr/bin

BASE_DIR="$(dirname "$0")"
BASE_NAME="wordlist-german"
WORDLIST="${BASE_DIR}/${BASE_NAME}.txt"
WORDLIST_LOWERCASE="${BASE_DIR}/${BASE_NAME}-lowercase.txt"
WORDLIST_DICEWARE="${BASE_DIR}/${BASE_NAME}-diceware.txt"

usage() {
  >&2 echo "usage: import file"
}

included() {
  local word="$1"
  grep --word-regexp --ignore-case --quiet "${word}" "${WORDLIST}"
}

valid() {
  local word="$1"
  echo "${word}" | LC_ALL=C grep --extended-regexp --quiet "^[A-Za-z][a-z]{2,6}$"
}

add() {
  local word="$1"
  local tmp="$(mktemp)"
  echo "${word}" >> "${WORDLIST}"
  sort --ignore-case "${WORDLIST}" > "${tmp}" && mv "${tmp}" "${WORDLIST}"
}

if [[ $# -ne 1 ]]; then
  usage
  exit 1
fi

file=$1

if [[ ! -f "${file}" ]]; then
  usage
  exit 1
fi

while read word; do
  included "${word}" && continue
  if ! valid "${word}"; then
    >&2 echo "invalid word: \"${word}\""
    continue
  fi
  add "${word}"
done < "${file}"
